try{
  try{
  _use();
  }catch(err){
  }
}catch(err){
}